### ISSUE TITLE
R-C3D for processing Charades dataset

### ISSUE THREAD

**Issue by LiliMeng** [VisionLearningGroup/R-C3D#3]
Thanks a lot for providing the open-source code!

Could you provide the pre-processing file for R-C3D? 

Highly appreciate your time and help!

**Comment by huijuan88** [comment]
It is already in preprocess folder.


On Dec 8, 2017, at 12:40, LiliMeng <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks a lot for providing the open-source code!

Could you provide the pre-processing file for R-C3D?

Highly appreciate your time and help!

**Comment by LiliMeng** [comment]
Thanks a lot! 

It seems that only ActivityNet preprocess is in preprocess folder, not Charades.

Thanks again!

**Comment by dansuthar** [comment]
@LiliMeng Looks like the folders for both Charades and THUMOS has been left out from this git repo.

**Comment by huijuan88** [comment]
The codes for thumos'14 and charades are released.
