### ISSUE TITLE
Window size for generating roi

### ISSUE THREAD

**Issue by ivyvideo** [VisionLearningGroup/R-C3D#38]
Thanks for your great contribution!
And I have one question about the window size for generating roi in generate_roidb_512.py
![image](https://user-images.githubusercontent.com/42105211/44646290-1ba69980-aa0d-11e8-9d6c-2a0d6047b974.png)
As shown above, you create a sliding window whose size is 512 to collect the data used for training, what confusing me is whether this parameter a empirical parameter? Or it is used after analysis on the thumos dataset?

**Comment by huijuan88** [comment]
Usually, it should roughly cover the longest activity duration in that fps.

On Aug 27, 2018, at 03:26, ivyvideo <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for your great contribution!
And I have one question about the window size for generating roi in generate_roidb_512.py
[image]<https://user-images.githubusercontent.com/42105211/44646290-1ba69980-aa0d-11e8-9d6c-2a0d6047b974.png>
As shown above, you create a sliding window whose size is 512 to collect the data used for training, what confusing me is whether this parameter a empirical parameter? Or it is used after statistics?

**Comment by ivyvideo** [comment]
@huijuan88 Thanks for reply! Got it.
And it has nothing to do with the output of Conv5b which has 512 channels, right?

**Comment by huijuan88** [comment]
No relationship with it.


On Aug 28, 2018, at 04:10, ivyvideo <notifications@github.com<mailto:notifications@github.com>> wrote:


@huijuan88<https://github.com/huijuan88> Thanks for reply! Got it.
And it has nothing to do with the output of Conv5b which has 512 channels, right?

**Comment by ivyvideo** [comment]
ok, thank you so much!
