### ISSUE TITLE
activitynet_iter_30000_3fps.caffemodel

### ISSUE THREAD

**Issue by jetyingjia** [VisionLearningGroup/R-C3D#5]
Thanks a lot for sharing the code.
I am confused about this model?(activitynet_iter_30000_3fps.caffemodel)
a. It is a classification model or detection model?
b. how to get this model?
Thank you in advance!

**Comment by huijuan88** [comment]
It’s classification model for initialization, pretrained on ActivityNet ground truth segments.


On Dec 19, 2017, at 20:26, jetyingjia <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks a lot for sharing the code.
I am confused about this model?(activitynet_iter_30000_3fps.caffemodel)
a. It is a classification model or detection model?
b. how to get this model?
Thank you in advance!

**Comment by dansuthar** [comment]
@jetyingjia Your question b still remains unanswered I guess.

**Comment by sunnyxiaohu** [comment]
Hi, huijuan
Have you evaluated the performance of thumos14 when using "activitynet_iter_30000_3fps.caffemodel" for pretraining ? It seems that it would be more helpful if using "activitynet_iter_30000_3fps.caffemodel" to initialize instead of "Sports-1M" .

**Comment by dansuthar** [comment]
@jetyingjia The model is available at https://drive.google.com/file/d/131Cpuq1FndydeHzu38TY0baiS-uyN71w/view
