### ISSUE TITLE
How to get ucf101.caffemode

### ISSUE THREAD

**Issue by fanxx17** [VisionLearningGroup/R-C3D#61]
How to get UCF101.caffemodel if I want to train THUMOS14? Thank you very much

**Comment by huijuan88** [comment]
There is a link to it in experiments/thumos14/ .




On Dec 28, 2020, at 4:32 AM, fanxx17 <notifications@github.com<mailto:notifications@github.com>> wrote:



How to get UCF101.caffemodel if I want to train THUMOS14? Thank you very much

**Comment by fanxx17** [comment]
thank you for your team's share and your enthusiastic answer

**Comment by fanxx17** [comment]
the problem was solved, thank you
